# Generated by Django 4.1.5 on 2023-01-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
