# Generated by Django 4.1.7 on 2023-04-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_machine_onlinestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='pet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pet', verbose_name='綁定寵物'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='機器名稱'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='onlineStatus',
            field=models.BooleanField(default=False, verbose_name='上線狀態'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(verbose_name='寵物生日'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='content',
            field=models.TextField(verbose_name='寵物敘述'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='寵物照顧人'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=256, verbose_name='寵物名稱'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pettype', verbose_name='寵物種類'),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='寵物種類描述'),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='typename',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='寵物種類'),
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.FloatField(blank=True, null=True, verbose_name='數據值'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pet', verbose_name='寵物ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recordtype', verbose_name='記錄種類'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='type',
            field=models.CharField(max_length=255, verbose_name='紀錄種類'),
        ),
    ]
