# Generated by Django 4.2.3 on 2023-07-25 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='寵物生日'),
        ),
    ]
