# Generated by Django 4.2.3 on 2023-07-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pet_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fcm_Token'),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='typename',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='寵物種類'),
        ),
    ]
