# Generated by Django 4.2.3 on 2023-08-02 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_fcmtoken_token_alter_pettype_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='紀錄時間'),
        ),
    ]
